### PR TITLE
Remove All Error in your App

### PR DESCRIPTION
**Pull request by Ghayyas**
Hi I Have remove All Error in YOur App. I write your code and i find some bugs. I spent my Hole day and remove all bugs from your app.. Hope you Like my Work

Thank you..

### CODE REVIEW

**Comment by smkamranqadri** [comment]
It's great, will check and defiantly merged code after review and let you know.

**Comment by smkamranqadri** [comment]
It's great, will check and defiantly merged code after review and let you know.

**Comment by smkamranqadri** [comment]
No thing find useful to merge, if you want to contribute then integrate sessions in it and then include quiz section.

**Comment by Ghayyas** [comment]
Dear Have you tried to run your app??  Is its workings fine??

**Comment by smkamranqadri** [comment]
Yes before pushing to github and if you insist I will do shortly then get back to you.

**Comment by smkamranqadri** [comment]
checked and found bug connect-flash because of express-session was not integrated and bug of user create which also fixed

**Comment by smkamranqadri** [comment]
wishes to merged your code but there are a lots of unnecessary changes that's make me to avoid merge and fix by my self

**Pull request closed without merging**
